<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                            http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <groupId>fr.fuzeblocks</groupId>
   <artifactId>HomePlugin</artifactId>
   <version>${revision}</version>
   <packaging>pom</packaging>

   <name>HomePlugin</name>
   <description>[Created by fuzeblocks]</description>

   <modules>
       <module>core</module>
       <module>profiles/legacy</module>
       <module>profiles/modern</module>
   </modules>

   <properties>
       <revision>0.0.0</revision>
       <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
       <maven.deploy.skip>true</maven.deploy.skip>
   </properties>

   <distributionManagement>
       <repository>
           <id>github</id>
           <url>https://maven.pkg.github.com/fuzeblocks/HomePlugin</url>
       </repository>
   </distributionManagement>

   <repositories>
       <repository>
           <id>xenondevs</id>
           <url>https://repo.xenondevs.xyz/releases</url>
       </repository>
       <repository>
           <id>placeholderapi</id>
           <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
       </repository>
       <repository>
           <id>spigotmc-repo</id>
           <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
       </repository>
       <repository>
           <id>sonatype</id>
           <url>https://oss.sonatype.org/content/groups/public/</url>
       </repository>
       <repository>
           <id>jitpack.io</id>
           <url>https://jitpack.io</url>
       </repository>
   </repositories>
</project>
