<?xml version="1.0" encoding="utf-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.fuzeblocks.homeplugin</groupId>
    <artifactId>modern</artifactId>
    <packaging>jar</packaging>

    <parent>
        <groupId>fr.fuzeblocks</groupId>
        <artifactId>HomePlugin</artifactId>
        <version>0.8.7-warps_dev-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <name>HomePlugin - Modern</name>
    <description>HomePlugin - Modern</description>

    <properties>
        <maven.compiler.release>25</maven.compiler.release>
    </properties>

    <repositories>
        <repository>
            <id>xenondevs</id>
            <url>https://repo.xenondevs.xyz/releases</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>xyz.xenondevs.invui</groupId>
            <artifactId>invui</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.21.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}/../../src/main/java</sourceDirectory>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>move-plugin-yml</id>
                        <phase>none</phase>
                    </execution>
                    <execution>
                        <id>move-javadoc</id>
                        <phase>none</phase>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <failOnError>false</failOnError>
                    <excludePackageNames>
                        fr.fuzeblocks.homeplugin.gui.legacy:fr.fuzeblocks.homeplugin.gui.legacy.*
                    </excludePackageNames>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>25</release>
                    <excludes>
                        <exclude>**/gui/legacy/**/*.java</exclude>
                        <exclude>fr/fuzeblocks/homeplugin/gui/legacy/**/*.java</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                        <version>9.8</version>
                    </dependency>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm-commons</artifactId>
                        <version>9.8</version>
                    </dependency>
                    <dependency>
                        <groupId>org.vafer</groupId>
                        <artifactId>jdependency</artifactId>
                        <version>2.14</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>

</project>