Config:
  Connector:
     TYPE: "YAML" #MYSQL ou YAML
      #Optional
     HOST: "localhost"
     PORT: 3306
     USERNAME: "root"
     PASSWORD: ""
     DATABASE: "HomePlugin"
  Redis:
     UseRedis: false
     #Optional
     HOST: "localhost"
     PORT: 6379
     SSL: false
     PASSWORD: ""
  Language:
    Type: FRENCH #ENGLISH, FRENCH

  Spawn:
    Spawn-teleportation-permission: "HomePlugin.spawn.teleportation"
    SetSpawn-permission: "HomePlugin.spawn.setspawn"
  Home:
    Home-limite-for-player: 3
    Home-limite-permission-for-bypass: "HomePlugin.home.bypass"
  Task:
    Task-duration: 3 #second
    UseTitle: true
    UseMessage: false
    Add-particles-after-teleport: true
