Config:
  Language: FRENCH
  Connector:
    TYPE: "YAML" #MYSQL ou YAML
    #Optional
    HOST: "localhost"
    PORT: 3306
    USERNAME: "root"
    PASSWORD: ""
    DATABASE: "HomePlugin"
  Redis:
    UseRedis: false
    #Optional
    HOST: "localhost"
    PORT: 6379
    SSL: false
    PASSWORD: ""
  Home:
    DefaultHomeLimit: 3
    Teleportation:
      Task-duration: 3 #second
      UseTitle: true
      UseMessage: false
      Add-particles-after-teleport: true
