name: HomePlugin
version: '${project.version}'
main: fr.fuzeblocks.homeplugin.HomePlugin
api-version: '1.18'
load: STARTUP
authors: [fuzeblocks]
description: [Created by fuzeblocks]
commands:
  home:
    description: Se tp a un de ses homes
  sethome:
    description: Sert a poser un home
  spawn:
    description: Sert a se tp au spawn
  setspawn:
    description: Sert a set le spawn
  delspawn:
    description: Sert a supprimer le spawn
  delhome:
    description: Sert a supprimer un home
