<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                            http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <parent>
       <groupId>fr.fuzeblocks</groupId>
       <artifactId>HomePlugin</artifactId>
       <version>${revision}</version>
       <relativePath>../pom.xml</relativePath>
   </parent>

   <groupId>fr.fuzeblocks.homeplugin</groupId>
   <artifactId>core</artifactId>
   <packaging>jar</packaging>

   <name>HomePlugin - Core</name>
   <description>HomePlugin - Shared core</description>

   <properties>
       <maven.compiler.release>11</maven.compiler.release>
   </properties>

   <build>
       <sourceDirectory>${project.basedir}/src/main/java</sourceDirectory>
       <resources>
           <resource>
               <directory>${project.basedir}/src/main/resources</directory>
               <includes>
                   <include>plugin.yml</include>
                   <include>french.yml</include>
                   <include>english.yml</include>
                   <include>spanish.yml</include>
                   <include>config.yml</include>
                   <include>custom.yml</include>
                   <include>ukrainian.yml</include>
                   <include>russian.yml</include>
                   <include>german.yml</include>
                   <include>turkish.yml</include>
               </includes>
               <filtering>true</filtering>
           </resource>
       </resources>
       <plugins>
           <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-compiler-plugin</artifactId>
               <version>3.11.0</version>
               <configuration>
                   <release>11</release>
               </configuration>
           </plugin>
           <plugin>
               <groupId>org.apache.maven.plugins</groupId>
               <artifactId>maven-javadoc-plugin</artifactId>
               <version>3.4.0</version>
               <configuration>
                   <encoding>UTF-8</encoding>
                   <reportOutputDirectory>${project.basedir}/../docs</reportOutputDirectory>
                   <destDir>.</destDir>
               </configuration>
               <executions>
                   <execution>
                       <id>generate-javadocs</id>
                       <phase>package</phase>
                       <goals>
                           <goal>javadoc</goal>
                       </goals>
                   </execution>
               </executions>
           </plugin>
       </plugins>
   </build>

   <dependencies>
       <dependency>
           <groupId>redis.clients</groupId>
           <artifactId>jedis</artifactId>
           <version>5.2.0</version>
           <scope>compile</scope>
       </dependency>
       <dependency>
           <groupId>me.clip</groupId>
           <artifactId>placeholderapi</artifactId>
           <version>2.11.6</version>
           <scope>provided</scope>
       </dependency>
       <dependency>
           <groupId>com.yworks</groupId>
           <artifactId>yguard</artifactId>
           <version>4.1.0</version>
           <scope>compile</scope>
       </dependency>
       <dependency>
           <groupId>org.spigotmc</groupId>
           <artifactId>spigot-api</artifactId>
           <version>1.20.4-R0.1-SNAPSHOT</version>
           <scope>provided</scope>
       </dependency>
       <dependency>
           <groupId>org.jetbrains</groupId>
           <artifactId>annotations</artifactId>
           <version>26.0.2</version>
           <scope>compile</scope>
       </dependency>
       <dependency>
           <groupId>org.junit.jupiter</groupId>
           <artifactId>junit-jupiter</artifactId>
           <version>5.11.3</version>
           <scope>test</scope>
       </dependency>
       <dependency>
           <groupId>com.github.MilkBowl</groupId>
           <artifactId>VaultAPI</artifactId>
           <version>1.7</version>
           <scope>provided</scope>
       </dependency>
       <dependency>
           <groupId>net.kyori</groupId>
           <artifactId>adventure-platform-bukkit</artifactId>
           <version>4.4.1</version>
       </dependency>
       <dependency>
           <groupId>org.bstats</groupId>
           <artifactId>bstats-bukkit</artifactId>
           <version>3.0.2</version>
           <scope>compile</scope>
       </dependency>
   </dependencies>
</project>
