<?xml version="1.0" encoding="utf-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.fuzeblocks.homeplugin</groupId>
    <artifactId>legacy</artifactId>
    <packaging>jar</packaging>

    <parent>
      <groupId>fr.fuzeblocks</groupId>
      <artifactId>HomePlugin</artifactId>
      <version>0.8.7-warps_dev-SNAPSHOT</version>
      <relativePath>../../pom.xml</relativePath>
    </parent>


    <name>HomePlugin - Legacy</name>
    <description>HomePlugin - Legacy</description>

    <properties>
        <revision>0.0.0</revision>
        <maven.compiler.release>11</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <repositories>
        <repository>
          <id>xenondevs-releases</id>
          <name>xenondevs repository</name>
          <url>https://repo.xenondevs.xyz/releases</url>
        </repository>

    </repositories>

    <dependencies>
        <dependency>
          <groupId>xyz.xenondevs.invui</groupId>
          <artifactId>invui-core</artifactId>
          <version>1.49</version>
        </dependency>
        <dependency>
            <groupId>xyz.xenondevs.invui</groupId>
            <artifactId>inventory-access-r1</artifactId>
            <version>1.49</version>
        </dependency>

        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.20.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}/../../src/main/java</sourceDirectory>
        <resources>
            <resource>
                <directory>${project.basedir}/../../src/main/resources</directory>
                 <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>move-javadoc</id>
                        <phase>none</phase>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.12.0</version>
                <configuration>

                    <sourcepath>${project.basedir}/../../src/main/java</sourcepath>
                    <subpackages>fr.fuzeblocks.homeplugin.core:fr.fuzeblocks.homeplugin.other:fr.fuzeblocks.homeplugin.gui.legacy</subpackages>
                    <excludePackageNames>fr.fuzeblocks.homeplugin.gui.modern.*</excludePackageNames>
                    <excludes>
                        <exclude>fr/fuzeblocks/homeplugin/core/audience/PaperAudienceProvider.java</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <release>11</release>
                    <excludes>
                        <exclude>fr/fuzeblocks/homeplugin/gui/modern/**</exclude>
                        <exclude>fr/fuzeblocks/homeplugin/core/audience/PaperAudienceProvider.java</exclude>
                    </excludes>
                    </configuration>
            </plugin>
        </plugins>
    </build>

</project>