name: Maven Package

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of pom.xml
        settings-path: ${{ github.workspace }}/.github

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven  
      run: mvn deploy -s ${{ github.workspace }}/.github/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
